########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]

# Use the Kit Template repo configuration as a base. Only override things specific to the repo.
import_configs = [
    "${root}/_repo/deps/repo_kit_tools/kit-template/repo.toml",
    "${root}/_repo/deps/repo_kit_tools/kit-template/repo-external-app.toml",
]


# Repository Name. It is used for solution name and final package name
name = "kit-streamer"

[repo_build]
# These are necessary to avoid a repo_build failure where the source/apps directory
# is expected to always exist.
fetch."platform:linux-x86_64".before_pull_commands = [
    ["mkdir", "--parents", "${root}/source/apps"],
]

# Mute this command, don't emit to console.
fetch."platform:windows-x86_64".before_pull_commands = [
    ["powershell", "-Command", "New-Item -ItemType Directory -Path ${root}/source/apps -ErrorAction SilentlyContinue", ";", "Write-Host 'Done'"],
]

# If caching do not try to cache extensions. These will come from the NGC Kit Extension Registry.
fetch."token:cache==true".after_pull_commands = []


[repo_build.build]
enabled = true
"platform:windows-x86_64".enabled = false

[repo_build.msbuild]
# If set to true will attempt to link to host's Visual Studio and Windows SDK installations.
# This is needed if C++ compilation is needed on Windows, and repo_build.build.enabled is set to true.
link_host_toolchain = false

# Filter on Visual Studio version e.g.: Visual Studio 2022. Empty string will match all years and prioritize the newest.
vs_version = "vs2022"

# Visual Studio path; This will be used if the user would like to point to a specific VS installation rather than rely on heuristic locating.
# vs_path = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\"

# Filter specifically to "Enterprise", "Professional", or "Community" editions of Visual Studio
# vs_edition = "Community"

# Filter by Visual Studio installations that have installed this version of the MSVC compiler.
# msvc_version = "v142"

# Filter by Visual Studio installations that ship with MSBuild of this major version.
# msbuild_version = "17"

# Windows SDK version
# winsdk_version = "10.0.17763.0"

# Windows SDK path; This will prevent needing to dynamically locate an installation by guesswork.
# winsdk_path = "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0"

# Disable linbuild until we have a public image available.
[repo_build.docker]
enabled = false

[repo_build.fetch.pip]
# List of pip files to pip install from (in order)
files_to_pull = [
    "${root}/tools/deps/pip.toml"
]

# Do not gather Python dependency licenses
licensing_enabled = false

# Do not try to publish a pip cache to S3
publish_pip_cache = false

########################################################################################################################
# Test Runner
########################################################################################################################

[repo_test.suites.alltests]
kind = "glob_and_exec"
path = "${test_root}"

# Run all test
include = [
    "tests-*${shell_ext}"
]
exclude = [
    # exclude all apps by default
    # note: if you develop an app that needs to be tested remove the following line
    "tests-omni.app.*${shell_ext}"
]

# Disable certain tests for aarch64, see OM-87812 for details.
"platform:linux-aarch64".exclude = [
    "tests-omni.app.new_exts_demo_mini*",
    "tests-omni.app.my_app*",
]

########################################################################################################################
# Benchmarks
########################################################################################################################

[repo_bench.benchmarks.extension_benchmark]
description = "Extension Benchmark"
commands = [
    [
        '${root}/repo${shell_ext}', 'test', '--from-package', '--', '--benchmark',
        '--/exts/omni.kit.test/testExtMaxParallelProcesses=1',
        '--/exts/omni.kit.test/benchmarkFingerPrint/cpu_name="${cpu_name}"',
        '--/exts/omni.kit.test/benchmarkFingerPrint/gpu_name="${gpu_name}"',
    ]
]

########################################################################################################################
# Extensions publisher
########################################################################################################################

[repo_publish_exts]

# Extensions to publish, include and exclude among those discovered by kit. Wildcards are supported.
exts.include = [
]
exts.exclude = []

# verify before publishing
publish_verification = true

########################################################################################################################
# Extensions precacher
########################################################################################################################

[repo_precache_exts]
# Apps to run and precache
apps = [
    "${root}/source/apps/omni.app.conditioning_for_precise_visual_generative_ai.kit",
    "${root}/source/apps/omni.app.conditioning_for_precise_visual_generative_ai_streaming.kit",
]

registries = [
    { name = "kit/default", url = "https://ovextensionsprod.blob.core.windows.net/exts/kit/prod/107/shared" },
    { name = "kit/sdk", url = "https://ovextensionsprod.blob.core.windows.net/exts/kit/prod/sdk/${kit_version_short}/${kit_git_hash}" },
    { name = "kit/community", url = "https://dw290v42wisod.cloudfront.net/exts/kit/community" },
]

########################################################################################################################
# Documentation building
########################################################################################################################

[repo_docs]

# extension docs
[repo_docs.kit]
extensions = [
]

########################################################################################################################
# Launcher publish and deploy
########################################################################################################################

[repo_deploy_launcher]
enabled = true

[repo_deploy_launcher.slack]
enabled = false

[repo_deploy_launcher.tokens]
app_name = "My App"
slug = "my_app"


########################################################################################################################
# Packaging
########################################################################################################################

[repo_package.packages.fat_package]
root = "_build/$${platform}/$${config}"
archive_name = "${conf:repo.name}-fat"
# omniverse_flow_version_scheme sets package name to the format:
# archive_name@{build_version}+{gitbranch}.{builder_id}.{githash}.{build_environment}.{host_platform}.{archive_format}
# e.g. kit-app-template-thin@2024.1.0+custom-app-stuff.0.12345678.local.linux-x86_64.zip
omniverse_flow_version_scheme=true
package_per_config = true                   # By default we only build + package release.
append_config = true                        # Set to true to append release/debug config to package name.
archive_format = "zip"                      # We support "7z", "zip", "tar.gz", "tar.bz2"
windows_max_path_length = 0
#build_version = "${file:${config_root}/tools/VERSION.md}"  # It's ignored when omniverse_flow_version_scheme is true

files = [
    ["**"],
]
files_exclude = [
    ["_*/**"],
    [".*/**"],
    ["**/*.pdb"],
    ["**/*.exp"],
    ["baseapp/**"],
    ["extsbuild/**"],
    ["cache/**"],
    ["data/**"],
    ["logs/**"],
    ["apps/kit.portable"],
    ["**/__pycache__"],
    ["**/_repo/**"],
]
"linux-x86_64".files_strip = []


[repo_package.packages.thin_package]
root = "_build/$${platform}/$${config}"
archive_name = "${conf:repo.name}-thin"
omniverse_flow_version_scheme=true
package_per_config = true
append_config = true
archive_format = "zip"
windows_max_path_length = 0
#build_version = "${file:${config_root}/tools/VERSION.md}"

files = [
    ["**"],
]
files_exclude = [
    ["_*/**"],
    [".*/**"],
    ["**/*.pdb"],
    ["**/*.exp"],
    ["kit/**"],
    ["extscache/**"],
    ["extsbuild/**"],
    ["baseapp/**"],
    ["cache/**"],
    ["data/**"],
    ["logs/**"],
    ["apps/kit.portable"],
    ["**/__pycache__"],
    ["**/_repo/**"],
]
"linux-x86_64".files_strip = []
