appName: streamer

image_streamer:
  repository: "nvcr.io/nvidia/omniverse/conditioning-for-precise-visual-generative-ai-streaming"
  tag: "1.0.0"
  pullPolicy: "Always"
  port_min1: 47995
  port_max1: 48012
  port_min2: 49000
  port_max2: 49007
  port1: 8011
  port2: 8111
  port3: 49100

resources:
  limits:
    # cpu: 8000m
    # memory: 30144Mi
    nvidia.com/gpu: 1
  requests:
    # cpu: 8000m
    # memory: 30144Mi
    nvidia.com/gpu: 1

global:
  imagePullSecretName: ""