apiVersion: v1
kind: Service
metadata:
  name: playground
  labels:
    app.kubernetes.io/name: playground
    app.kubernetes.io/instance: playground
spec:
  ports:
    - port: {{ .Values.image_playground.servicePort }}
      targetPort: {{ .Values.image_playground.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
