apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
      app.kubernetes.io/instance: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName }}
        app.kubernetes.io/instance: {{ .Values.appName }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecretName }}
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.image.containerPort }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
