apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
spec:
  ports:
    - port: {{ .Values.image.servicePort }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
