# App Builder
FROM python:3.12-slim as builder

WORKDIR /app
COPY . .

RUN pip install -r requirements.txt

# Production Image
FROM nvcr.io/nvidia/distroless/python:3.12-v3.4.2

# Copy the installed packages
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages

WORKDIR /app
COPY . .

CMD ["python3", "imagegen_stub.py"]